SUBJECTS = {
    "数据科学与人工智能": [
        "Machine Learning（机器学习）",
        "Deep Learning（深度学习）",
        "Data Science（数据科学）",
        "TensorFlow",
        "AI / Artificial Intelligence（人工智能）",
    ],
    "计算机科学与编程": [
        "Python",
        "Java（Java）",
        "C++（C加加）",
        "React / Web Development（React / 网页开发）",
        "Algorithms / Data Structures（算法与数据结构）",
        "Programming Fundamentals（编程基础）",
    ],
    "云计算与架构": [
        "Google Cloud Platform (GCP)（谷歌云平台）",
        "AWS（亚马逊云服务）",
        "Cloud Computing（云计算）",
        "Kubernetes（K8s / 容器编排）",
        "Architecting / Infrastructure（架构设计 / 基础设施）",
        "Serverless / Applications（无服务器架构 / 应用开发）",
    ],
    "网络安全与合规": [
        "Cybersecurity（网络安全）",
        "Security（安全）",
        "IT Fundamentals / Support（IT基础 / 技术支持）",
        "CompTIA（CompTIA认证）",
        "Risk / Incident Response（风险 / 应急响应）",
        "Compliance（合规）",
    ],
    "医学、公共卫生与生命科学": [
        "Public Health（公共卫生）",
        "Epidemiology（流行病学）",
        "Anatomy / Physiology（解剖学 / 生理学）",
        "Clinical Research / Trials（临床研究 / 试验）",
        "COVID-19（新冠病毒）",
        "Cancer（癌症）",
    ],
    "商科与管理学": [
        "Project Management（项目管理）",
        "Business Strategy / Foundations（商业战略 / 基础）",
        "Marketing / Digital Marketing（市场营销 / 数字营销）",
        "Leadership（领导力）",
        "Human Resources (HR)（人力资源管理）",
        "Operations / Supply Chain（运营管理 / 供应链）",
    ],
    "金融与投资": [
        "Corporate Finance（公司金融）",
        "Financial Markets（金融市场）",
        "Investment / Portfolio（投资 / 投资组合）",
        "FinTech / Blockchain（金融科技 / 区块链）",
        "Accounting（会计）",
        "Valuation / Modeling（估值 / 建模）",
    ],
    "法律与国际事务": [
        "International Law（国际法）",
        "American Law / Contract Law（美国法 / 合同法）",
        "Intellectual Property（知识产权）",
        "Cyber Conflicts（网络冲突）",
        "Human Rights（人权）",
        "Global Diplomacy（全球外交）",
    ],
    "人文、艺术与社会科学": [
        "Music (Production, Business, Theory)（音乐：制作、商业、理论）",
        "Photography / Design（摄影 / 设计）",
        "Positive Psychology（积极心理学）",
        "Philosophy / History（哲学 / 历史）",
        "Creative Writing（创意写作）",
        "Social Science / Sociology（社会科学 / 社会学）",
    ],
    "语言学习与教学": [
        "English (Academic, Business, Writing)（英语：学术、商务、写作）",
        "Chinese / Mandarin（中文 / 普通话）",
        "Spanish（西班牙语）",
        "Learn / Speak（学习 / 口语）",
        "TESOL / Teach English（对外英语教学）",
        "Russian（俄语）",
    ],
}

SUBJECT_LIST = [
    "数据科学与人工智能",
    "Machine Learning",
    "机器学习",
    "Deep Learning",
    "深度学习",
    "Data Science",
    "数据科学",
    "TensorFlow",
    "AI",
    "Artificial Intelligence",
    "人工智能",
    "计算机科学与编程",
    "Python",
    "Java",
    "Java",
    "C++",
    "C加加",
    "React",
    "Web Development",
    "React",
    "网页开发",
    "Algorithms",
    "Data Structures",
    "算法与数据结构",
    "Programming Fundamentals",
    "编程基础",
    "软件开发",
    "后端开发",
    "前端开发",
    "云计算与架构",
    "Google Cloud Platform",
    "GCP",
    "谷歌云平台",
    "AWS",
    "亚马逊云服务",
    "Cloud Computing",
    "云计算",
    "Kubernetes",
    "K8s",
    "容器编排",
    "Architecting",
    "Infrastructure",
    "架构设计",
    "基础设施",
    "Serverless",
    "Applications",
    "无服务器架构",
    "应用开发",
    "网络安全与合规",
    "Cybersecurity",
    "网络安全",
    "Security",
    "安全",
    "IT Fundamentals",
    "IT Support",
    "IT基础",
    "技术支持",
    "CompTIA",
    "CompTIA认证",
    "Risk",
    "Incident Response",
    "风险",
    "应急响应",
    "Compliance",
    "合规",
    "医学、公共卫生与生命科学",
    "Public Health",
    "公共卫生",
    "Epidemiology",
    "流行病学",
    "Anatomy",
    "Physiology",
    "解剖学",
    "生理学",
    "Clinical Research",
    "Clinical Trials",
    "临床研究",
    "临床试验",
    "COVID-19",
    "新冠病毒",
    "Cancer",
    "癌症",
    "商科与管理学",
    "Project Management",
    "项目管理",
    "Business Strategy",
    "Business Foundations",
    "商业战略",
    "商业基础",
    "Marketing",
    "Digital Marketing",
    "市场营销",
    "数字营销",
    "Leadership",
    "领导力",
    "Human Resources",
    "HR",
    "人力资源管理",
    "Operations",
    "Supply Chain",
    "运营管理",
    "供应链",
    "金融与投资",
    "金融",
    "股票",
    "理财",
    "炒股",
    "股价",
    "市场",
    "经济",
    "Corporate Finance",
    "公司金融",
    "Financial Markets",
    "金融市场",
    "Investment",
    "Portfolio",
    "投资",
    "投资组合",
    "FinTech",
    "Blockchain",
    "金融科技",
    "区块链",
    "Accounting",
    "会计",
    "Valuation",
    "Modeling",
    "估值",
    "建模",
    "法律与国际事务",
    "International Law",
    "国际法",
    "American Law",
    "Contract Law",
    "美国法",
    "合同法",
    "Intellectual Property",
    "知识产权",
    "Cyber Conflicts",
    "网络冲突",
    "Human Rights",
    "人权",
    "Global Diplomacy",
    "全球外交",
    "人文、艺术与社会科学",
    "Music",
    "Music Production",
    "Music Business",
    "Music Theory",
    "音乐",
    "音乐制作",
    "音乐商业",
    "音乐理论",
    "Photography",
    "Design",
    "摄影",
    "设计",
    "Positive Psychology",
    "积极心理学",
    "Philosophy",
    "History",
    "哲学",
    "历史",
    "Creative Writing",
    "创意写作",
    "Social Science",
    "Sociology",
    "社会科学",
    "社会学",
    "语言学习与教学",
    "English",
    "Academic English",
    "Business English",
    "English Writing",
    "英语",
    "学术英语",
    "商务英语",
    "英语写作",
    "Chinese",
    "Mandarin",
    "中文",
    "普通话",
    "Spanish",
    "西班牙语",
    "口语",
    "TESOL",
    "Teach English",
    "对外英语教学",
    "Russian",
    "俄语",
]
